name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install -y gcc
      - name: build
        run: CC=${{ matrix.compiler }} make
